django-project/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('vouchers.urls')),
    path('sites-admin/', admin.site.urls),
]

django-project/vouchers/urls.py
from django.urls import path

from . import views
app_name = 'vouchers'
urlpatterns = [
    path('', views.index, name='index'),
    path('consume', views.consume, name='consume'),
    path('success/<str:voucher_code>', views.success, name='success'),
    path('error/<int:error_code>', views.error, name='error')
]

django-project/vouchers/models.py
from django.db import models

# Create your models here.
class Voucher(models.Model):
    voucher_code=models.CharField(max_length=50)
    discount_value= models.IntegerField()
    discount_type= models.CharField(max_length=3)
    pub_date= models.DateTimeField('date published')
    usage_number= models.IntegerField()
    max_usage= models.IntegerField(default=3)

    def __str__(self):
        return f"{self.voucher_code} used {self.usage_number}/{self.max_usage}"

    def still_can_use(self):
        return self.usage_number< self.max_usage

django-project/vouchers/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import F
from django.template import loader
from django.http import Http404
from .models import Voucher



def _get_context(message='', error_message='', inline_error_message=''):
    """return default context"""
    available_vouchers= Voucher.objects.filter(usage_number__lt=F('max_usage'))
    context={
        'available_vouchers': available_vouchers,
        'message': message,
        'error_message': error_message,
        'inline_error_message': inline_error_message
    }

    return context

def index(request):
    template = loader.get_template('home/index.html')
    return render(request, 'home/index.html', _get_context())

def success(request, voucher_code):
    """success page if everything is fine, redirect here to avoid send request on refresh"""
    print(voucher_code)
    code= get_object_or_404(Voucher, voucher_code= voucher_code)
    context= _get_context(message=f'congratulation you got {code.discount_value}{code.discount_type} off on your purchase')
    return render(request, 'home/index.html', context)

def error(request, error_code):
    """error page if voucher is exceed the number of usage, redirect here to avoid send request on refresh"""
    errors={
        1:{'error':'this voucher exceed the allowed usage number!', 'type':'inline'},
        2:{'error':'this voucher is invalid!', 'type':'block'}
    }
    print(error_code)
    context=None
    errorInfo=errors.get(error_code, None)
    print(errorInfo)
    if (errorInfo==None):
        raise Http404()
    
    if errorInfo['type']=='inline':
        context= _get_context(inline_error_message=errorInfo['error'])
    else:
        context= _get_context(error_message=errorInfo['error'])
    
    return render(request, 'home/index.html', context)


def consume(request):
    voucher_code= request.POST['voucher_code']
    code=None
    try:
        code=Voucher.objects.get(voucher_code= voucher_code)
    except:
        return redirect('error/2')

    if (code.usage_number >=code.max_usage ):
        return redirect('/error/1')

    code.usage_number+=1
    code.save()

    return redirect(f'/success/{code.voucher_code}')

# Create your views here.

django-project/vouchers/templates/home/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Voucher with Django</title>
    {% block style %}
    {% endblock %}
  </head>
  <body>
    <div class="container">
    
        {% block content %}
        {% endblock %}
        
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

django-project/vouchers/templates/home/index.html
{% extends 'home/base.html' %}

{% block content %}


<div class="row mt-5">
  <div class="col-4 col-sm-auto d-flex flex-row justify-content-left">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <form method="post" action="{% url 'vouchers:consume' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleInputEmail1">Enter Vocuher Code</label>
            <input type="text" class="form-control" id="voucherInput" aria-describedby="voucherhelp" name="voucher_code"
              placeholder="Voucher code">
            <small id="voucherHelp" class="form-text text-muted">{{inline_error_message}}</small>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>

  </div>
  <div class="col-8 col-sm-auto">
    <h3>Available vouchers</h3>

    {% for voucher in available_vouchers %}

    <h3><span class="badge badge-info voucher-code">{{voucher.voucher_code}}</span></h3>
    {% endfor %}

  </div>
</div>

<h1 class="text-primary"></h1>

{% if message.strip %}
<div class="alert alert-primary" role="alert">
  {{message}}
</div>
{% endif %}

{% if error_message.strip %}
<div class="alert alert-danger" role="alert">
  {{error_message}}
</div>
{% endif %}


{% block script %}
<script>
  $(function () {
    $(".voucher-code").click(function () {
      var el = $(this);
      var code = el.text();
      $("#voucherInput").attr('value', code);
    })
  });
</script>
{% endblock script %}


{% block style %}
<style>
  .voucher-code {
    cursor: pointer;
  }
</style>
{% endblock style %}



{% endblock %}